# Generated by Django 3.2.8 on 2023-02-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, verbose_name='图片名称')),
                ('src', models.CharField(default='', max_length=500, verbose_name='纠正文本')),
                ('dest', models.CharField(default='', max_length=500, verbose_name='纠错后文本')),
                ('owner', models.CharField(default='', max_length=100, verbose_name='')),
                ('status', models.CharField(default='', max_length=100, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'pic',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(default='', max_length=500, verbose_name='纠正文本')),
                ('dest', models.CharField(default='', max_length=500, verbose_name='纠错后文本')),
                ('owner', models.CharField(default='', max_length=100, verbose_name='')),
                ('status', models.CharField(default='', max_length=100, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'db_table': 'text',
            },
        ),
    ]
